# Generated by Django 3.2.8 on 2021-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('user_fullname', models.TextField()),
                ('user_name', models.TextField()),
                ('user_password', models.TextField(editable=False)),
                ('user_contact', models.CharField(max_length=10, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
