# Generated by Django 3.2.8 on 2021-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDetails',
            fields=[
                ('des_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('des_name', models.CharField(max_length=50)),
                ('price_adult', models.IntegerField(max_length=200)),
                ('price_child', models.IntegerField(max_length=200)),
                ('price_infant', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='TravellerDetails',
            fields=[
                ('traveller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('traveller_name', models.CharField(max_length=100)),
                ('traveller_age', models.IntegerField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papago.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('travel_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('total_adults', models.IntegerField()),
                ('total_child', models.IntegerField(blank=True, null=True)),
                ('total_infant', models.IntegerField(blank=True, null=True)),
                ('travel_date', models.DateField()),
                ('des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papago.destinationdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papago.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papago.userdetails')),
            ],
        ),
    ]
