# Generated by Django 3.2.8 on 2021-11-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papago', '0002_auto_20211101_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdetails',
            name='des_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='travel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
