# Generated by Django 3.2.8 on 2021-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papago', '0004_alter_userdetails_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdetails',
            name='des_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='travel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travellerdetails',
            name='traveller_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
